{% set name = "fast-array-utils" %}
{% set version = "1.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fast_array_utils-{{ version }}.tar.gz
  sha256: 15bb57a38f60ef89207189fd10b8d6a65d6ce25a9c802cf5f1485498f7837c1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-docstring-description >=1.1.1
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - fast_array_utils
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://icb-fast-array-utils.readthedocs-hosted.com/
  summary: Fast array utilities with minimal dependencies.
  license: MPL-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - mschilli87
